<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0GHR3KF" ignored="0" name="Test" tests="37" failures="16" timestamp="2021-03-10T16:26:03 ICT" time="181.283" errors="0">
  <testcase name="User01" time="1.383" classname="com.vn.test.UserTest"/>
  <testcase name="User02" time="1.473" classname="com.vn.test.UserTest"/>
  <testcase name="User03" time="1.274" classname="com.vn.test.UserTest"/>
  <testcase name="User04" time="1.259" classname="com.vn.test.UserTest"/>
  <testcase name="User05" time="1.318" classname="com.vn.test.UserTest"/>
  <testcase name="rediectInsertUser" time="0.25" classname="com.vn.test.UserTest">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8888/user/insertUser?] but found [http://localhost:8888/user/insert]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8888/user/insertUser?] but found [http://localhost:8888/user/insert]
at com.vn.test.UserTest.rediectInsertUser(UserTest.java:227)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- rediectInsertUser -->
  <testcase name="rediectListtUser" time="0.243" classname="com.vn.test.UserTest"/>
  <testcase name="User06" time="1.523" classname="com.vn.test.UserTest">
    <failure type="java.lang.AssertionError" message="Lỗi : Không nhập mã hợp lệ">
      <![CDATA[java.lang.AssertionError: Lỗi : Không nhập mã hợp lệ
at com.vn.test.UserTest.User06(UserTest.java:144)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- User06 -->
  <testcase name="User09" time="1.632" classname="com.vn.test.UserTest"/>
  <testcase name="User10" time="1.406" classname="com.vn.test.UserTest"/>
  <testcase name="User07" time="1.41" classname="com.vn.test.UserTest"/>
  <testcase name="User08" time="1.433" classname="com.vn.test.UserTest">
    <failure type="java.lang.AssertionError" message="Lỗi : Không nhập mã hợp lệ">
      <![CDATA[java.lang.AssertionError: Lỗi : Không nhập mã hợp lệ
at com.vn.test.UserTest.User08(UserTest.java:170)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- User08 -->
  <testcase name="Staff11" time="1.534" classname="com.vn.test.EmployeeTest"/>
  <testcase name="Staff12" time="1.502" classname="com.vn.test.EmployeeTest"/>
  <testcase name="Staff13" time="1.466" classname="com.vn.test.EmployeeTest"/>
  <testcase name="Staff14" time="1.324" classname="com.vn.test.EmployeeTest"/>
  <testcase name="Staff15" time="1.368" classname="com.vn.test.EmployeeTest"/>
  <testcase name="Staff16" time="1.587" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff16(EmployeeTest.java:132)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff16 -->
  <testcase name="Staff17" time="1.842" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff17(EmployeeTest.java:146)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff17 -->
  <testcase name="Staff19" time="1.707" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff19(EmployeeTest.java:160)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff19 -->
  <testcase name="Staff20" time="1.584" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff20(EmployeeTest.java:174)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff20 -->
  <testcase name="Staff21" time="1.464" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff21(EmployeeTest.java:188)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff21 -->
  <testcase name="Staff22" time="1.754" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff22(EmployeeTest.java:202)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff22 -->
  <testcase name="Staff23" time="1.656" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff23(EmployeeTest.java:216)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff23 -->
  <testcase name="Staff24" time="1.853" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff24(EmployeeTest.java:230)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff24 -->
  <testcase name="Staff25" time="1.486" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff25(EmployeeTest.java:244)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff25 -->
  <testcase name="Staff26" time="1.606" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Khong nhap ma hop le">
      <![CDATA[java.lang.AssertionError: Lỗi: Khong nhap ma hop le
at com.vn.test.EmployeeTest.Staff26(EmployeeTest.java:258)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Staff26 -->
  <testcase name="rediectInsertStaff" time="0.392" classname="com.vn.test.EmployeeTest">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8888/staff/insert?] but found [http://localhost:8888/staff/insert]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8888/staff/insert?] but found [http://localhost:8888/staff/insert]
at com.vn.test.EmployeeTest.rediectInsertStaff(EmployeeTest.java:290)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- rediectInsertStaff -->
  <testcase name="rediectListStaff" time="0.656" classname="com.vn.test.EmployeeTest"/>
  <testcase name="emptyPassword" time="0.386" classname="com.vn.test.LoginTest"/>
  <testcase name="emptyUsername" time="0.21" classname="com.vn.test.LoginTest"/>
  <testcase name="rediectAdmin" time="0.984" classname="com.vn.test.LoginTest"/>
  <testcase name="rediectDepart" time="0.462" classname="com.vn.test.AdminTest"/>
  <testcase name="rediectRecord" time="0.394" classname="com.vn.test.AdminTest"/>
  <testcase name="rediectStaff" time="30.689" classname="com.vn.test.AdminTest"/>
  <testcase name="rediectSummarize" time="0.073" classname="com.vn.test.AdminTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Không nhập mã vẫn hợp lệ">
      <![CDATA[java.lang.AssertionError: Lỗi: Không nhập mã vẫn hợp lệ
at com.vn.test.AdminTest.rediectSummarize(AdminTest.java:130)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- rediectSummarize -->
  <testcase name="rediectUser" time="0.06" classname="com.vn.test.AdminTest">
    <failure type="java.lang.AssertionError" message="Lỗi: Không nhập mã vẫn hợp lệ">
      <![CDATA[java.lang.AssertionError: Lỗi: Không nhập mã vẫn hợp lệ
at com.vn.test.AdminTest.rediectUser(AdminTest.java:64)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- rediectUser -->
</testsuite> <!-- Test -->
